### ISSUE TITLE
Suggestion:  Multi language and buttons to control time.

### ISSUE THREAD

**Issue by CHrvita** [Rinnegatamante/sleepwalkers-vita#1]
First of all, congratulations on this gem of a game for all ages.
It would be amazing if it will also have multi language support and I think the gameplay could be improved by using L and R to rewind and fast-forward the little sleepwalker.
Thank you again and this port is beautiful.

**Comment by Rinnegatamante** [comment]
The game has no multilanguage support. As for the triggers, i'll add it in next release.
